from pathlib import Path
from typing import Dict, Any
import sys
import os

# Add parent directory to path
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '../..')))

from app.config_parser import InfrastructureConfig
from app.utils.logger import setup_logger

logger = setup_logger(__name__)


class TerraformGenerator:
    """Generate Terraform configuration files from user input"""
    
    @staticmethod
    def generate_aws_config(config: InfrastructureConfig) -> str:
        """
        Generate Terraform configuration for AWS
        
        Args:
            config: Infrastructure configuration
            
        Returns:
            Terraform configuration as string
        """
        # Build tags
        tags_hcl = "\n    ".join([
            f'{key} = "{value}"'
            for key, value in config.tags.items()
        ]) if config.tags else 'ManagedBy = "Streamlit-Terraform"'
        
        # Generate AMI data source or use provided AMI
        ami_config = '''
# Data source to get latest Amazon Linux 2 AMI
data "aws_ami" "selected" {
  most_recent = true
  owners      = ["amazon"]

  filter {
    name   = "name"
    values = ["amzn2-ami-hvm-*-x86_64-gp2"]
  }

  filter {
    name   = "virtualization-type"
    values = ["hvm"]
  }
}
''' if not config.ami_id else ''
        
        ami_reference = 'data.aws_ami.selected.id' if not config.ami_id else f'"{config.ami_id}"'
        
        terraform_config = f'''# Generated Terraform Configuration
# Provider: {config.provider}
# Region: {config.region}
# Generated by Streamlit Terraform Deployer

terraform {{
  required_version = ">= 1.0"
  
  required_providers {{
    aws = {{
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }}
  }}
}}

provider "aws" {{
  region = "{config.region}"
}}
{ami_config}
# EC2 Instance
resource "aws_instance" "main" {{
  ami           = {ami_reference}
  instance_type = "{config.instance_type}"

  tags = {{
    {tags_hcl}
  }}

  lifecycle {{
    create_before_destroy = true
  }}
}}

# Outputs
output "instance_id" {{
  description = "ID of the EC2 instance"
  value       = aws_instance.main.id
}}

output "instance_public_ip" {{
  description = "Public IP address of the EC2 instance"
  value       = aws_instance.main.public_ip
}}

output "instance_private_ip" {{
  description = "Private IP address of the EC2 instance"
  value       = aws_instance.main.private_ip
}}

output "instance_state" {{
  description = "State of the EC2 instance"
  value       = aws_instance.main.instance_state
}}
'''
        
        return terraform_config
    
    @staticmethod
    def generate_azure_config(config: InfrastructureConfig) -> str:
        """
        Generate Terraform configuration for Azure (placeholder)
        
        Args:
            config: Infrastructure configuration
            
        Returns:
            Terraform configuration as string
        """
        raise NotImplementedError("Azure provider not yet implemented in Phase 2")
    
    @staticmethod
    def generate_gcp_config(config: InfrastructureConfig) -> str:
        """
        Generate Terraform configuration for GCP (placeholder)
        
        Args:
            config: Infrastructure configuration
            
        Returns:
            Terraform configuration as string
        """
        raise NotImplementedError("GCP provider not yet implemented in Phase 2")
    
    @staticmethod
    def write_config_to_file(
        config: InfrastructureConfig,
        output_dir: Path
    ) -> Path:
        """
        Write generated Terraform configuration to file
        
        Args:
            config: Infrastructure configuration
            output_dir: Directory to write files to
            
        Returns:
            Path to generated main.tf file
        """
        output_dir = Path(output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)
        
        # Generate configuration based on provider
        if config.provider == "aws":
            tf_config = TerraformGenerator.generate_aws_config(config)
        elif config.provider == "azure":
            tf_config = TerraformGenerator.generate_azure_config(config)
        elif config.provider == "gcp":
            tf_config = TerraformGenerator.generate_gcp_config(config)
        else:
            raise ValueError(f"Unsupported provider: {config.provider}")
        
        # Write to main.tf
        main_tf_path = output_dir / "main.tf"
        with open(main_tf_path, "w") as f:
            f.write(tf_config)
        
        logger.info(f"Generated Terraform configuration at: {main_tf_path}")
        
        return main_tf_path
    
    @staticmethod
    def preview_config(config: InfrastructureConfig) -> str:
        """
        Generate preview of Terraform configuration without writing to file
        
        Args:
            config: Infrastructure configuration
            
        Returns:
            Terraform configuration as string
        """
        if config.provider == "aws":
            return TerraformGenerator.generate_aws_config(config)
        elif config.provider == "azure":
            return TerraformGenerator.generate_azure_config(config)
        elif config.provider == "gcp":
            return TerraformGenerator.generate_gcp_config(config)
        else:
            raise ValueError(f"Unsupported provider: {config.provider}")
